services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
