services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "4000:4000"
    command: "npm run build-and-start"
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
